services:
  - docker
language: go
go:
  - '1.7'
env:
  global:
  - REPO=quay.io/wantedly/slack-notifier
  - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
  - TAG=$BRANCH-${TRAVIS_COMMIT::8}
  - secure: HLV1zIuwvyVRmX9xeHqmjgOE3jdH8dCo7bIER+GCVrlUVy0mqoW/4y/bMfRkgxcAH7yTSbDl1BsPKOyhlN+k5pM2bQRO2z4wL3tFLk0WtUJEa6VHamsndyM/RU4Q9LIWqwPq7ZLKmT28SL3JHpY7LrnEHW51ah6T9ss/NSNTAx9uN6g2HFzON0JyJqiIGoXQLwqBVSHa75D/O1eHKJNr/bNn3qMSWYGmWcGeu0pGtnGVG6rt5lvQvX9P33OasrgBPiuoqQBNdBbMqjznZJwj9CpBmjcBFLEaGIy8UBY5VXa7fdF7t3UKuVLVnd/WSi6wNa2ImNBrJVMQx21An7TtK/yAjl6Ml+yjWDseqeMS9arIOlSIk+7D8abdSmYOrKJEISrslRrUo2jJjT1lvVXD7A9gUHLZtruIAxPFLeY1NLJGpfhd0U66YwWT7CrhWoGmlt0lv1qeu9Us57mTLc10SWSIQV4c7mnGPdj2WhTcwOXvOaChFtXPonnhwWkqH4gGAdcOGRp0o54jFSBha33GGOv34xJR5jE/GFXJtyjC97N3+k+UYxyF7AwEvRxj5/RL9pKfRJbK8L4N5IJMGK2FE6m9gHKC1Bo+I0DFvy47g5Kb1yRc2kFe5uO9vqPrgO+YjKuyMmUzzuasXNFw8kzG4K7LbLjm+fkKmE3FuBykoK8=
  - secure: iG7c5nktJFmAmg8daCDo+uWtHU0Qp7MUHBMV/Lqhs+T5VLM/V5avLIGJLwEs3U9ATvYurljIcGXT7bCAdCv+mRwaMCBBcyiGOZgiXkFw4XUXfaEQlDGvBuVsyRiGsoDqcWl66wQG9KhLxu5fjqrXtkRzg7yvIb8+HaybqsiNa+XsYKqUX9n+SuUq3OAYRYFgv3gmDvwsLrjR9soOsDKrkcML1mC8HHZmWgESxGx929zytOxw8Ag33RZUsVp6I8SN2nwQW9OIn9yv7IhdIuwvBaLR4FZXwOPIZkAHTUWJU3RzzdSzKUJuZ/2dmm3Nu5+12ar7ZWla6rSz8awUjWAzBzQs2pG5Xbvz3QCM1J+0GkwMeHoCiO7NqVulXhfxkVmCw0ed3+lyOy3H8udMbr8euDjKTrKr46wJEPzanZ7Um4RhbT0Bd6Ye1He8tCyITPMCpijXmqftWjDkCDOEIU/FINxnATgaK7BTWAZvQalXkwUb5RgI4NDwDDCbwu2OKKya0tV5PQa2PD4J8S5/LC+5uikAHORSyfHYk01VyfC+WuFzWH+++1msuHk7GhGQZ0Qd2OfA08eRPbcTPN0tpGv9RyP1dpsZT2M6nraY3h8WisKu9IPKZC12kIUkGquZEwXF3r4z84tN9dkByWe3XwjOZ4l6Ugv5pg0xGarGxkLrxpc=
  - secure: VTuHFiqYKLkUo0BfzdvUjKi8lignPfwefEBYE05WhXembDCUa2BRpZJTjivGPUulkI1vJgdpAELaopnR10fpC3+5EC+BYqaJywUwhPWUNUZNnS53ZnJIe2hTgOQmVA/joOY+cYBsnkl2oBJLO/AIQH7Iwx81UOB0rQqRDxcFBL0HuPcVjWF9KRT4wCvqo08xmyyRDQAzJ5mkupxDJ3hWWRkgvbCnooLGqpesnXspIXietROSm0sYStS7DogG9dCFavalmel74RlHuxah+pbpjhsDqZ0+zoZXI/fPVEYB/xKOXy7Kp1KVqcYnXZUXkH13mYPKuhZsrSbYhRODMbpjc0ElX8w8BnxOombCLEyFC5OCU7qtYVDzopZ1e7iAgrqLoN72W3P4TjmdHkQWUKwxpmMIGh7/Aaw6zn2PmGrtR6Jb65QvbJdrvdpbNf8hVM3n+evX+XcCc8KhOaHGWevdNtNg3QxzsVXz7CPq4s8JxHnbrcFnXXUnHGpgzFUsx+z79utGXD4Rpag1VrGQyEExDzErjGV/3thbuBwFJ/+RNnY9QiA6d+Fx1Oae1i76DVB8EPqz4u40lmKae6DkXNF4yA9WHYacFuTPWsl3zBXn8E4nKBam6I+LpHHj2GV3JM8gFwV2PhPAHLUWndJ2IJlywkHP/AkUwnMAKgYCbrTMA6I=
script:
  - echo ${TRAVIS_COMMIT::8}
  - make ci-build
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    all_branches: true
