language: go
go:
  - '1.7'
services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

env:
  global:
    - REPO=quay.io/wantedly/slack-notification
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
    - TAG=$BRANCH-${TRAVIS_COMMIT::8}

before_script:
  - glide install

script:
  - echo ${TRAVIS_COMMIT::8}
  - make ci-build

deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    all_branches: true
